/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.prueba02;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import org.neo4j.driver.Record;

/**
 *
 * @author anton
 */
public class Buscadorpre extends javax.swing.JFrame {
  private Neo4jClass mineo;
    /**
     * Creates new form Buscadorpre
     */
    public Buscadorpre() {
        initComponents();
        mineo = new Neo4jClass ("bolt://localhost:7687","neo4j","123");
        
        modelo = new DefaultListModel();
        modelo2 = new DefaultListModel();
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listacaballos = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaconcursos = new javax.swing.JList<>();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Añadir ganaderia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 47, 130, -1));

        jButton2.setText("Añadir concurso");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 78, 130, -1));

        jButton3.setText("Añadir caballo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 117, 130, -1));

        jButton4.setText("Eliminar ganaderia");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 47, 150, -1));

        jButton5.setText("Eliminar concurso");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 78, 150, -1));

        jButton6.setText("Eliminar caballo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 117, 150, -1));

        jButton7.setText("eliminar todo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        jButton8.setText("Cargar caballos y concursos disponibles");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 290, -1));

        jButton9.setText("Asignar participantes ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        listacaballos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listacaballos);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 128, 132));

        listaconcursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listaconcursos);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 128, 132));

        jButton10.setText("Asignar ganador");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 130, -1));

        jButton11.setText("Ver lista de concursos ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Insertar concurso
        String nombre = javax.swing.JOptionPane.showInputDialog("introduzca nombre concurso");
        int participantes = Integer.parseInt(javax.swing.JOptionPane.showInputDialog("introduzca numero participantes"));
        String impotancia = javax.swing.JOptionPane.showInputDialog("introduzca importancia concurso");
        mineo.inserConcurso(nombre, participantes, impotancia);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // Insertar caballo
        
        String nombre= (String)javax.swing.JOptionPane.showInputDialog("introducir nombre caballo");
        String Nacimiento= (String)javax.swing.JOptionPane.showInputDialog("introducir fecha nacimiento caballo");
        //String sexo= javax.swing.JOptionPane.showInputDialog("sexo caballo");
        String chip= (String)javax.swing.JOptionPane.showInputDialog("introducir chip caballo");
        String ganaderia= (String)javax.swing.JOptionPane.showInputDialog("introducir ganadaria a la que pertenece");
        mineo.inserCaballo(nombre, Nacimiento, chip);
        mineo.relacionarcaballoGanaderia(chip, ganaderia);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //añadir ganaderia
        String nombre = javax.swing.JOptionPane.showInputDialog("introduzca nombre ganadreia");
        String fundacion= javax.swing.JOptionPane.showInputDialog("Introduzca la fecha de fundacion");
        mineo.insertGanaderia(nombre, fundacion);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Eliminar ganaderia
        String nombre = javax.swing.JOptionPane.showInputDialog("introduzca nombre ganadreia");
        mineo.eliminarGanaderia(nombre);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        // Eliminar concurso
        String nombre = javax.swing.JOptionPane.showInputDialog("introduzca nombre concurso");
        mineo.eliminarConcurso(nombre);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        // Eliminar caballo
        String nombre = javax.swing.JOptionPane.showInputDialog("introduzca nombre caballo");
        mineo.eliminarCaballo(nombre);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        // elimina todo
        mineo.eliminarTodo();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Ganaderias g = new Ganaderias();
        List<Record> listac;
      listacaballos.removeAll();
      modelo.removeAllElements();
      listacaballos.setModel(modelo);
      listac = mineo.obtenerCaballo();
      for (int i=0;i<listac.size();i++){
          Record p = listac.get(i);
          System.out.println(p);
          String añadir = quitarcomas(p.get("c.nombreCaballo")+" "+p.get("c.fechaNacimiento")+"  "+p.get("c.chip").toString());
          modelo.addElement(añadir);
         System.out.println(añadir);
      }
       listacaballos.setModel(modelo);
       
       
       List<Record> listak;
      listaconcursos.removeAll();
      modelo2.removeAllElements();
      listaconcursos.setModel(modelo2);
      listak = mineo.obtenerConcurso();
      for (int i=0;i<listak.size();i++){
          Record p = listak.get(i);
          System.out.println(p);
          String añadir = quitarcomas(p.get("k.nombreConcurso")+"  ("+p.get("k.importanciaConcurso").toString()+")");
          modelo2.addElement(añadir);
         System.out.println(añadir);
      }
       listaconcursos.setModel(modelo2);
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String c = listacaballos.getSelectedValue().toString();
        String texto[] = c.split(" ");
        String chip = texto[3];
        System.out.println(chip);
        
        String j = listaconcursos.getSelectedValue().toString();
        String texto1[] = j.split(" ");
        String nombreConcurso = texto1[0];
        System.out.println(nombreConcurso);
        mineo.relacionarcaballoConcurso(chip, nombreConcurso);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       String c = listacaballos.getSelectedValue().toString();
        String texto[] = c.split(" ");
        String nombre = texto[0];
       
        
         String j = listaconcursos.getSelectedValue().toString();
        String texto1[] = j.split(" ");
        String concurso = texto1[0];
        
        
        mineo.asignarGanador(nombre,concurso);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
            Concursos c = new Concursos();
            c.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscadorpre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscadorpre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscadorpre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscadorpre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscadorpre().setVisible(true);
            }
        });
    }
    
    public static String quitarcomas(String c){
        String resultado ="";
        for(int i=0;i<c.length();i++){
           if(c.charAt(i)!= '"'){
            resultado +=c.charAt(i);
        }
        
    }
    return resultado;
    }
 
    private DefaultListModel modelo;
    private DefaultListModel modelo2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listacaballos;
    private javax.swing.JList<String> listaconcursos;
    // End of variables declaration//GEN-END:variables
}
